# Generated by Django 5.0.4 on 2024-04-11 15:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('origin', models.CharField(default='default', max_length=255, verbose_name='Провайдер')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_item_images', verbose_name='Картинка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productlist.product', verbose_name='Товар')),
                ('who_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь добавивший')),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2024, 4, 11, 20, 24, 14, 530473), verbose_name='Дата создания')),
                ('name', models.CharField(max_length=50, verbose_name='Название списка')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('uid', models.CharField(blank=True, default='sfCFyKHmGopGTXpIURxs', max_length=100, verbose_name='Кастомная ссылка')),
                ('members', models.ManyToManyField(blank=True, related_name='shared_product_lists', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lists', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, null=True, related_name='product_list', to='productlist.productitem')),
            ],
        ),
    ]
