# Generated by Django 5.0.4 on 2024-04-10 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.UUID('5c06885b-2e6b-4622-a128-91e124ac23d6'), unique=True, verbose_name='Уникальный идентификатор')),
                ('name', models.CharField(max_length=50, verbose_name='Название Семьи')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=50, verbose_name='Название списка')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lists', to='productlist.family')),
                ('products', models.ManyToManyField(related_name='product_list', to='productlist.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, verbose_name='Дата создания')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productlist.product', verbose_name='Товар')),
                ('who_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productlist.profile', verbose_name='Пользователь добавивший')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productlist.profile', verbose_name='Владелец семьи'),
        ),
    ]
