# Generated by Django 5.0.4 on 2024-04-11 19:34

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='date_created',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2024, 4, 12, 0, 34, 43, 145043), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='uid',
            field=models.CharField(blank=True, default=uuid.UUID('55e3a071-7ac5-4e85-bb4e-b8e09b18c629'), max_length=100, unique=True, verbose_name='Кастомная ссылка'),
        ),
    ]
