# Generated by Django 5.0.4 on 2024-04-11 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(default='default', max_length=255, verbose_name='Провайдер'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_item_images', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='family',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9af05b79-8d0f-4b42-9938-d61233b1ae4d'), unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
