# Generated by Django 5.0.4 on 2024-04-11 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0002_product_origin_productitem_image_alter_family_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='who_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь добавивший'),
        ),
        migrations.AlterField(
            model_name='family',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец семьи'),
        ),
        migrations.AlterField(
            model_name='family',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a1372d22-0acb-4765-a849-8fb4487fd3ea'), unique=True, verbose_name='Уникальный идентификатор'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
