# Generated by Django 5.0.4 on 2024-04-12 07:50

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0003_alter_product_price_alter_productlist_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='productlist',
            name='date_created',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2024, 4, 12, 12, 50, 22, 828551), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='uid',
            field=models.CharField(blank=True, default=uuid.UUID('51a2bb09-73a6-4773-94fa-faedffbf271f'), max_length=100, unique=True, verbose_name='Кастомная ссылка'),
        ),
    ]
